# Generated by Django 6.0.5 on 2026-05-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_commentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='author',
            new_name='user',
        ),
    ]
