# Generated by Django 6.0.5 on 2026-05-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_author_commentary_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="text",
            new_name="content",
        ),
    ]
